/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gymmanagement;


import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shazi
 */
public class AfterLogin extends javax.swing.JFrame  {

        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
        String updateId;
      
    public AfterLogin() {
        super("Gym Management System");  
        initComponents();
        conn=DBCONNECTION.ConnectDb();
         jPanel5.setVisible(false);
        jPanel4.setVisible(true);
        jScrollPane1.setBackground(new Color(0,0,0,0));
        registrationno.setEditable(false);
          Voice voice;
        VoiceManager vm = VoiceManager.getInstance();
        voice = vm.getVoice("kevin16");
        voice.allocate();
        voice.speak("     Welcome to gym management System");
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        userName = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        instructorId = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        contactNo = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        NewMemberName = new javax.swing.JTextField();
        NewMemberAge = new javax.swing.JTextField();
        NewMemberRegistration = new javax.swing.JTextField();
        NewMemberHeight = new javax.swing.JTextField();
        NewMemberContactNo = new javax.swing.JTextField();
        NewMemberAddress = new javax.swing.JTextField();
        NewMemberEmail = new javax.swing.JTextField();
        NewMemberMale = new javax.swing.JRadioButton();
        NewMemberFemale = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel36 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        memberName = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        male1 = new javax.swing.JRadioButton();
        female1 = new javax.swing.JRadioButton();
        jLabel42 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        address1 = new javax.swing.JTextField();
        contactNo1 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        registrationno = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        height1 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        memberemail = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel56 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Navigation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bell MT", 0, 36), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\shazi\\Downloads\\icons8-account-48.png")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("My Account");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 200, 50));

        jButton3.setBackground(new java.awt.Color(0, 51, 102));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Add New Member");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setMaximumSize(new java.awt.Dimension(89, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(89, 23));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 200, 50));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 200, 50));

        jButton5.setBackground(new java.awt.Color(0, 51, 102));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Search Members");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jButton5MouseDragged(evt);
            }
        });
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 200, 50));

        jButton9.setBackground(new java.awt.Color(0, 51, 102));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Generate Slip");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jButton9MouseDragged(evt);
            }
        });
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton9MouseExited(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 200, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 250, 510));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\shazi\\Desktop\\prussian321.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 520));

        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\shazi\\Downloads\\resize-159877288713533381iconperson.jpg")); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 140, 170));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Personal Information");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 160, 20));

        jLabel7.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Instructor Id :");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 100, -1));

        jLabel8.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name :");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("User Name :");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contact Information");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 150, 20));

        jLabel11.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address :");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 60, -1));

        jLabel12.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Contact No :");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Gender : ");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 820, 10));
        jPanel5.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 150, -1));
        jPanel5.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 150, -1));
        jPanel5.add(instructorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 150, -1));
        jPanel5.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 150, -1));
        jPanel5.add(contactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 150, -1));

        male.setOpaque(false);
        jPanel5.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        female.setOpaque(false);
        jPanel5.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Male");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        jLabel15.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Female");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\shazi\\Desktop\\Background general.jpg")); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 570));

        jPanel3.add(jPanel5, "card2");

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Orbitron", 0, 48)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Welcome");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        jLabel31.setFont(new java.awt.Font("Orbitron", 0, 48)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("To");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        jLabel32.setFont(new java.awt.Font("Orbitron", 0, 48)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Gym");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        jLabel33.setFont(new java.awt.Font("Orbitron", 0, 48)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(240, 240, 240));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Management");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        jLabel34.setFont(new java.awt.Font("Orbitron", 0, 48)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("System");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\shazi\\Desktop\\Webp.net-resizeimage.png")); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 590));

        jPanel3.add(jPanel4, "card3");

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\shazi\\Downloads\\resize-159877288713533381iconperson.jpg")); // NOI18N
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 130, 180));
        jPanel6.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 860, 30));

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Personal Information");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Contact Information");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        jLabel20.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Member Name :");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jLabel21.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Age :");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jLabel22.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Contact No :");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        jLabel23.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Gender :");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        jLabel24.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Registration No :");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, -1));

        jLabel25.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Email :");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));

        jLabel26.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Height :");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        jLabel27.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Address :");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, -1));
        jPanel6.add(NewMemberName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 160, -1));
        jPanel6.add(NewMemberAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 160, -1));
        jPanel6.add(NewMemberRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 160, -1));
        jPanel6.add(NewMemberHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 160, -1));
        jPanel6.add(NewMemberContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 160, -1));
        jPanel6.add(NewMemberAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, 160, -1));

        NewMemberEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewMemberEmailActionPerformed(evt);
            }
        });
        jPanel6.add(NewMemberEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 160, -1));

        NewMemberMale.setOpaque(false);
        jPanel6.add(NewMemberMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        NewMemberFemale.setOpaque(false);
        jPanel6.add(NewMemberFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        jLabel28.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Male");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 212, -1, -1));

        jLabel29.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Female");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 212, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 51, 153));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add Member");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 140, 40));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\shazi\\Desktop\\Background general.jpg")); // NOI18N
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 580));

        jPanel3.add(jPanel6, "card4");

        jPanel7.setPreferredSize(new java.awt.Dimension(1040, 540));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 850, 20));

        jScrollPane1.setBackground(new java.awt.Color(0, 51, 153));
        jScrollPane1.setOpaque(false);

        jTable1.setBackground(new java.awt.Color(0, 51, 102));
        jTable1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(240, 240, 240));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S/N", "Member Name", "Registration Number", "Age", "Address", "Contact No", "Gender", "Height", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setOpaque(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 860, 150));

        jLabel36.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(153, 153, 153));
        jLabel36.setText("Search");
        jPanel7.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Member Name", "Registration", "Email" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 120, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.setCaretColor(new java.awt.Color(240, 240, 240));
        jTextField1.setOpaque(false);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel7.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 60, 150, 30));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 0, 36), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel9.setOpaque(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Personal Information");
        jPanel9.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 160, 20));

        jLabel38.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Member Name :");
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));
        jPanel9.add(memberName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 150, -1));

        jLabel39.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Age:");
        jPanel9.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel40.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Gender : ");
        jPanel9.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel41.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Male");
        jPanel9.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        male1.setOpaque(false);
        jPanel9.add(male1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        female1.setOpaque(false);
        jPanel9.add(female1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jLabel42.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Female");
        jPanel9.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 171, -1, -1));
        jPanel9.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 150, -1));

        jLabel43.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Contact Information");
        jPanel9.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 150, 20));

        jLabel44.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Address :");
        jPanel9.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 60, -1));
        jPanel9.add(address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 150, -1));
        jPanel9.add(contactNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 150, -1));

        jLabel45.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Contact No :");
        jPanel9.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        jLabel46.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Registration Number :");
        jPanel9.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 160, -1));

        registrationno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationnoActionPerformed(evt);
            }
        });
        jPanel9.add(registrationno, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 150, -1));

        jLabel47.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Height :");
        jPanel9.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));
        jPanel9.add(height1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 150, -1));

        jLabel48.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Email :");
        jPanel9.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, -1, -1));

        memberemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberemailActionPerformed(evt);
            }
        });
        jPanel9.add(memberemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 150, -1));

        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        jButton8.setText("Reset");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 860, 280));

        jLabel35.setIcon(new javax.swing.ImageIcon("C:\\Users\\shazi\\Desktop\\Background general.jpg")); // NOI18N
        jPanel7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 550));

        jPanel3.add(jPanel7, "card5");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel8, "card6");

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel10.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 860, 20));

        jLabel50.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Member Name :");
        jPanel10.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel51.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Instructor Id :");
        jPanel10.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel52.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Registration Number :");
        jPanel10.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel53.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Timings :");
        jPanel10.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel54.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Membership Plans :");
        jPanel10.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel55.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Supplements :");
        jPanel10.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));
        jPanel10.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 240, -1));
        jPanel10.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 240, -1));
        jPanel10.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 240, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Batch Timings", "6:00 am to 11:00 am ", "3:00 pm to  6:00 pm", "7:00 pm to 12:00 am", " ", " " }));
        jPanel10.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 240, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("     ****************************************\t\n     *         Gorilla Fit Gymnasium        *");
        jScrollPane2.setViewportView(jTextArea1);

        jPanel10.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 370, 390));

        jLabel56.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(153, 153, 153));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("Receipt");
        jPanel10.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 200, 50));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "NitroTech", "Whey Protein", "Muscle Milk", "MyoFusion", "HydroWhey", "Serious MASS", "Fusion", "BeneProtein", "Monster Protein", "Elite", "Syntha-6" }));
        jPanel10.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 110, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Silver", "Premium", "Black Label" }));
        jPanel10.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 110, -1));

        jTextField5.setText("Membership Fee");
        jPanel10.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 120, -1));

        jTextField6.setText("Supplements Fee");
        jPanel10.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 120, -1));

        jButton10.setText("Print");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 120, 30));

        jLabel49.setIcon(new javax.swing.ImageIcon("C:\\Users\\shazi\\Desktop\\Background general.jpg")); // NOI18N
        jPanel10.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 540));

        jPanel3.add(jPanel10, "card7");

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -20, 910, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1196, 559));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           String mysql = "select * from Registration where UserName = ?  ";
                jPanel5.setVisible(true);
                jPanel4.setVisible(false);
                jPanel6.setVisible(false);
               
       
            
            try {
                pst=conn.prepareStatement(mysql);
                pst.setString(1,Login.userNameForLogin.getText() );
                rs=pst.executeQuery();
                 
                if(rs.next())
                {
                    userName.setText((rs.getString("UserName")));
                    name.setText(rs.getString("InstructorName"));
                    
                    instructorId.setText(rs.getString("InstructorId"));
                    if(rs.getString("Gender").equalsIgnoreCase("male"))
                    {
                        male.setSelected(true);
                    }
                    else
                    {
                        female.setSelected(true);
                    }
                    contactNo.setText(rs.getString("ContactNumber"));
                    
                    address.setText(rs.getString("Address"));
                    
                } else{
             JOptionPane.showMessageDialog(null, "Enter Correct Info"); 
          }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NewMemberEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewMemberEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewMemberEmailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try {
                String ins = "insert into MemberDetails(MemberName , RegistrationNumber , Age , Address , ContactNumber , Gender , Height , Email) values(?,?,?,?,?,?,?,?)"; 
                pst = conn.prepareCall(ins);
                pst.setString(1, NewMemberName.getText());
                pst.setString(2, NewMemberRegistration.getText());
                pst.setString(3, NewMemberAge.getText());
                
                pst.setString(4, NewMemberAddress.getText());
                pst.setString(5, NewMemberContactNo.getText());
                if(NewMemberMale.isEnabled())
                {
                    pst.setString(6, "Male");
                }
                else if (NewMemberFemale.isEnabled()) {
                    pst.setString(6, "Female");
                }
                pst.setString(7,NewMemberHeight.getText());
                pst.setString(8, NewMemberEmail.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Member added successfully");
               
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
               rs.close();
               pst.close();
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      jPanel5.setVisible(false);
      jPanel4.setVisible(false);
      jPanel6.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           
                this.dispose();
                Voice voice;
                VoiceManager vm = VoiceManager.getInstance();
                voice = vm.getVoice("kevin16");
                voice.allocate();
                voice.speak(" Good Bye See you again");
                
                Login login = new Login();
                login.setVisible(true);
            
        
       
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
      jButton1.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseDragged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jPanel5.setVisible(false);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(true);
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // Key Release
        if (jComboBox1.getSelectedIndex()<=0) {
            JOptionPane.showMessageDialog(rootPane, "Please Select an Option.....");
        } else {
            
            try {
                String sn,memberName,registration,email,age,address,contactnumber,gender,height;
                String str1 = jTextField1.getText();
                String sqll = "Select * from MemberDetails where " +option.trim()+ "=?";
                pst = conn.prepareStatement(sqll);
               
                pst.setString(1, str1);
                
                rs = pst.executeQuery();
                dtm = (DefaultTableModel) jTable1.getModel();
                dtm.setRowCount(0);
                
                if(rs.next())
                {
                    do {                        
                        sn = rs.getString("S/N");
                        memberName = rs.getString("MemberName");
                        registration = rs.getString("RegistrationNumber");
                        age = rs.getString("Age");
                        address = rs.getString("Address");
                        contactnumber = rs.getString("ContactNumber");
                        gender = rs.getString("Gender");
                        height = rs.getString("Height");
                        email = rs.getString("Email");
                        
                       dtm.addRow(new Object[]{sn,memberName,registration,age,address,contactnumber,gender,height,email});
                        
                    } while (rs.next());
                }
                pst.close();
                rs.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
            
        }
       
        
        
    }//GEN-LAST:event_jTextField1KeyReleased
        String option = "";
        DefaultTableModel dtm;
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
            int index = jComboBox1.getSelectedIndex();
            if(index<=0){
                dtm.setRowCount(0);
            }
            if(index==1)
            {
                option="MemberName"; // Variable name must be same as database
            }
             if(index==2)
            {
                option="RegistrationNumber";
            }
             if(index==3)
            {
                option="Email";
            }
            
            
             
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
       jButton1.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        jButton3.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
      jButton3.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
       jButton5.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        jButton5.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_jButton5MouseExited
public void clearFields()
{
    memberName.setText("");
    age.setText("");
    address1.setText("");
    contactNo1.setText("");
    registrationno.setText("");
    memberemail.setText("");
    height1.setText("");
    male1.setSelected(false);
    female1.setSelected(false);
}
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        if(memberName.getText().equals("")||age.getText().equals("")||height1.getText().equals("")||address1.getText().equals("")||contactNo1.getText().equals("")||registrationno.getText().equals("")||memberemail.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "please select from table");
        }
        else
        {   
            try {
                    String value1=memberName.getText();
                    String value2=registrationno.getText();
                    String value3=age.getText();
                    String value4=address1.getText();
                    String value5=contactNo1.getText();
                    String value6 ;
                    String value7 = height1.getText();
                    String value8 = memberemail.getText();
                    if(male1.isEnabled())
                    {
                         value6 = "male";
                    }
                    else
                        value6 = "Female";
                         
                     String sql="update MemberDetails set MemberName='"+value1+"' ,RegistrationNumber='"+value2+"',Age='"+value3+"',Address='"+value4+"',ContactNumber='"+value5+"',Gender='"+value6+"',Height='"+value7+"',Email='"+value8+"' where RegistrationNumber='"+value2+"'";
                      pst=conn.prepareStatement(sql);
                      int ok = JOptionPane.showConfirmDialog(rootPane, "Sure you want to update data", "Sure to update",JOptionPane.YES_NO_OPTION);
                    if(ok==0){
                      pst.execute();
                     JOptionPane.showMessageDialog(null, "Updated Succesfully");
                     clearFields();
                    }
                         
            } catch (SQLException ex) {
                Logger.getLogger(AfterLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }      
    }//GEN-LAST:event_jButton6ActionPerformed

    private void registrationnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationnoActionPerformed
        
    }//GEN-LAST:event_registrationnoActionPerformed

    private void memberemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberemailActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
//        String sn = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
//        try {
//                //mouseclicked
//                String get = "Select * from MemberDetails where S/N=?";
//                pst = conn.prepareStatement(get);
//                pst.setString(1,sn );
//                rs = pst.executeQuery();
//                if(rs.next())
//                {
//                    memberName.setText(rs.getNString("MemberName"));
//                    registrationno.setText((rs.getString("RegistrationNumber")));
//                    age.setText(rs.getString("Age"));
//                    address1.setText(rs.getString("Address"));
//                    contactNo1.setText(rs.getString("ContactNumber"));
//                    if(rs.getString("Gender").equalsIgnoreCase("male"))
//                    {
//                       male1.setSelected(true);
//                    }
//                    else
//                    {
//                        female1.setSelected(true);
//                    }
//                    height1.setText(rs.getString("Height"));
//                    memberemail.setText(rs.getString("Email"));
//                    
//                    
//                    
//                }
//                
//            } catch (SQLException ex) {
//               JOptionPane.showMessageDialog(rootPane, ex);
//            }
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int selectedRowIndex = jTable1.getSelectedRow();
                    memberName.setText(model.getValueAt(selectedRowIndex, 1).toString());
                    registrationno.setText(model.getValueAt(selectedRowIndex, 2).toString());
                    age.setText(model.getValueAt(selectedRowIndex, 3).toString());
                    address1.setText(model.getValueAt(selectedRowIndex, 4).toString());
                    contactNo1.setText(model.getValueAt(selectedRowIndex, 5).toString());
                    if((model.getValueAt(selectedRowIndex, 6).toString()).equalsIgnoreCase("male"))
                    {
                       male1.setSelected(true);
                    }
                    else
                    {
                        female1.setSelected(true);
                    }
                    height1.setText(model.getValueAt(selectedRowIndex, 7).toString());
                    memberemail.setText(model.getValueAt(selectedRowIndex, 8).toString());
            
      
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                
         if(memberName.getText().equals("")||age.getText().equals("")||height1.getText().equals("")||address1.getText().equals("")||contactNo1.getText().equals("")||registrationno.getText().equals("")||memberemail.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "please select from table");
        }else{
                int dialogResult = JOptionPane.showConfirmDialog(null, "do you want to delete the record ? ", "Warning" , JOptionPane.YES_NO_OPTION);
                if(dialogResult==JOptionPane.YES_OPTION){
        
            try {
             
                String query = "delete  from MemberDetails where  RegistrationNumber = ?  ";
                pst = conn.prepareStatement(query);
                 pst.setString(1,registrationno.getText() );
                
                pst.execute();
                
                JOptionPane.showMessageDialog(rootPane, "deleted successfully");
                clearFields();
                
                
                
                
            } catch (SQLException ex) {
                Logger.getLogger(AfterLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
         }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jTable1.setModel(new DefaultTableModel(null, new String[]{"sn","memberName","registration","age","address","contactnumber","gender","height","email"}));
        jComboBox1.setSelectedIndex(0);
        jTextField1.setText("");
        clearFields();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseDragged

    private void jButton9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseEntered
         jButton9.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_jButton9MouseEntered

    private void jButton9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseExited
         jButton9.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_jButton9MouseExited

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       jPanel5.setVisible(false);
        jPanel4.setVisible(false);
         jPanel6.setVisible(false);
          jPanel7.setVisible(false);
           jPanel8.setVisible(false);
            jPanel10.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       java.util.Date date = new java.util.Date();
       String date1 = date.toString();
       jTextArea1.setText(jTextArea1.getText()+"\n" + date1+"\n\n");
       jTextArea1.setText(jTextArea1.getText()+"Member Name : " + jTextField2.getText()+"\n");
       jTextArea1.setText(jTextArea1.getText()+"Instructor Id : " + jTextField3.getText()+"\n");
       jTextArea1.setText(jTextArea1.getText()+"Registration Number : " + jTextField4.getText()+"\n");
       
       
       jTextArea1.setText(jTextArea1.getText()+"Batch Timings : " + jComboBox2.getSelectedItem()+"\n");
        if(jComboBox4.getSelectedItem().toString().equalsIgnoreCase("silver"))
       {
           jTextField5.setText("50$");
           jTextArea1.setText(jTextArea1.getText()+"Membership : Silver "+" Price : 50$"+"\n");
           
       }
      else if(jComboBox4.getSelectedItem().toString().equalsIgnoreCase("premium"))
       {
           jTextField5.setText("70$");
           jTextArea1.setText(jTextArea1.getText()+"Membership : Premium "+" Price : 70$"+"\n");
       }
      else if(jComboBox4.getSelectedItem().toString().equalsIgnoreCase("black label"))
      {
          jTextField5.setText("100$");
          jTextArea1.setText(jTextArea1.getText()+"Membership : Black Label "+" Price : 100$"+"\n");
      }
      else
      {
          JOptionPane.showMessageDialog(rootPane, "Please select from ComboBox");
      }
       if(jComboBox3.getSelectedItem().toString().equalsIgnoreCase("Nitro Tech"))
       {
             jTextField6.setText("70$");
           jTextArea1.setText(jTextArea1.getText()+"Nitro Tech "+"\n");
       }
       else if(jComboBox3.getSelectedItem().toString().equalsIgnoreCase("Whey Protein"))
       {
            jTextArea1.setText(jTextArea1.getText()+"Supplement : Whey Protein"+" Price : 100$"+"\n");
       }
       else if(jComboBox3.getSelectedItem().toString().equalsIgnoreCase("Muscle Milk"))
       {
            jTextArea1.setText(jTextArea1.getText()+"Supplement : Muscle Milk"+" Price : 70$"+"\n");
       }
       else if(jComboBox3.getSelectedItem().toString().equalsIgnoreCase("Myofusion"))
       {
            jTextArea1.setText(jTextArea1.getText()+"Supplement : Myofysion"+" Price : 59$"+"\n");
       }
//       else if(jComboBox3.getSelectedItem().toString().equalsIgnoreCase("MyoFusion"))
//       {
//           jTextArea1.setText(jTextArea1.getText()+"Supplement : Myofysion"+" Price : 59$"+"\n");
//       }
       else if(jComboBox3.getSelectedItem().toString().equalsIgnoreCase("HydroWhey"))
       {
           jTextArea1.setText(jTextArea1.getText()+"Supplement : HydroWhey"+" Price : 109$"+"\n");
       }
       else if(jComboBox3.getSelectedItem().toString().equalsIgnoreCase("Serious Mass"))
       {
           jTextArea1.setText(jTextArea1.getText()+"Supplement : Serious Mass"+" Price : 200$"+"\n");
       }
       
       else if(jComboBox3.getSelectedItem().toString().equalsIgnoreCase("Fusion"))
       {
           jTextArea1.setText(jTextArea1.getText()+"Supplement : fusion"+" Price : 99$"+"\n");
       }
       else if(jComboBox3.getSelectedItem().toString().equalsIgnoreCase("BeneProtein"))
       {
           jTextArea1.setText(jTextArea1.getText()+"Supplement : BeneProtein"+" Price : 89$"+"\n");
       }
       else if(jComboBox3.getSelectedItem().toString().equalsIgnoreCase("Monster Protein"))
       {
            jTextArea1.setText(jTextArea1.getText()+"Supplement : Monster Protein"+" Price : 300$"+"\n");
       }
       else if(jComboBox3.getSelectedItem().toString().equalsIgnoreCase("Elite"))
       {
           jTextArea1.setText(jTextArea1.getText()+"Supplement : Elite"+" Price : 47$"+"\n");
       }
       else if(jComboBox3.getSelectedItem().toString().equalsIgnoreCase("Syntha-6"))
       {
           jTextArea1.setText(jTextArea1.getText()+"Supplement : Syntha-6"+" Price : 99$"+"\n");
       }
       
      
      
        
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AfterLogin().setVisible(true);
            }
        });
    }
   
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NewMemberAddress;
    private javax.swing.JTextField NewMemberAge;
    private javax.swing.JTextField NewMemberContactNo;
    private javax.swing.JTextField NewMemberEmail;
    private javax.swing.JRadioButton NewMemberFemale;
    private javax.swing.JTextField NewMemberHeight;
    private javax.swing.JRadioButton NewMemberMale;
    private javax.swing.JTextField NewMemberName;
    private javax.swing.JTextField NewMemberRegistration;
    private javax.swing.JTextField address;
    private javax.swing.JTextField address1;
    private javax.swing.JTextField age;
    private javax.swing.JTextField contactNo;
    private javax.swing.JTextField contactNo1;
    private javax.swing.JRadioButton female;
    private javax.swing.JRadioButton female1;
    private javax.swing.JTextField height1;
    private javax.swing.JTextField instructorId;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton male1;
    private javax.swing.JTextField memberName;
    private javax.swing.JTextField memberemail;
    private javax.swing.JTextField name;
    private javax.swing.JTextField registrationno;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
