/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gymmanagement;

import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author shazi
 */
public class Login extends javax.swing.JFrame {

        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
    public Login() {
        
        
        super("Login");
        initComponents();
       
        conn=DBCONNECTION.ConnectDb();
         userNameForLogin.setBackground(new Color(0,0,0,0));
        instructorIdForLogin.setBackground(new Color(0,0,0,0));
        passwordForLogin.setBackground(new Color(0,0,0,0));
         Voice voice;
        VoiceManager vm = VoiceManager.getInstance();
        voice = vm.getVoice("kevin16");
        voice.allocate();
        voice.speak("Please Login");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userNameForLogin = new javax.swing.JTextField();
        passwordForLogin = new javax.swing.JPasswordField();
        instructorIdForLogin = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        signInForLogin = new javax.swing.JButton();
        signUpForLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\shazi\\Desktop\\gym panel.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 130, 30));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 100, 30));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Instructor Id");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 110, 20));

        userNameForLogin.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        userNameForLogin.setForeground(new java.awt.Color(153, 153, 153));
        userNameForLogin.setText("Enter your username");
        userNameForLogin.setBorder(null);
        userNameForLogin.setOpaque(false);
        userNameForLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameForLoginFocusGained(evt);
            }
        });
        userNameForLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameForLoginActionPerformed(evt);
            }
        });
        jPanel1.add(userNameForLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 340, 30));

        passwordForLogin.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        passwordForLogin.setForeground(new java.awt.Color(153, 153, 153));
        passwordForLogin.setText("passwordad");
        passwordForLogin.setBorder(null);
        passwordForLogin.setOpaque(false);
        passwordForLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordForLoginFocusGained(evt);
            }
        });
        passwordForLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordForLoginActionPerformed(evt);
            }
        });
        jPanel1.add(passwordForLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 340, 30));

        instructorIdForLogin.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        instructorIdForLogin.setForeground(new java.awt.Color(153, 153, 153));
        instructorIdForLogin.setText("Enter your id");
        instructorIdForLogin.setBorder(null);
        instructorIdForLogin.setOpaque(false);
        instructorIdForLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                instructorIdForLoginFocusGained(evt);
            }
        });
        instructorIdForLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorIdForLoginActionPerformed(evt);
            }
        });
        jPanel1.add(instructorIdForLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 340, 30));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 340, 20));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 340, 20));

        jSeparator3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 340, 30));

        jCheckBox1.setOpaque(false);
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, -1, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Agree");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 429, 50, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(60, 139, 182));
        jLabel7.setText("<html>\n<body>\n<u> Terms And Conditions</u>\n</body>\n</html>");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 431, 140, -1));

        signInForLogin.setBackground(new java.awt.Color(0, 51, 102));
        signInForLogin.setForeground(new java.awt.Color(255, 255, 255));
        signInForLogin.setText("Sign In");
        signInForLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signInForLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                signInForLoginMouseDragged(evt);
            }
        });
        signInForLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInForLoginActionPerformed(evt);
            }
        });
        jPanel1.add(signInForLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 70, -1));

        signUpForLogin.setForeground(new java.awt.Color(0, 51, 153));
        signUpForLogin.setText("Sign Up");
        signUpForLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpForLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpForLoginActionPerformed(evt);
            }
        });
        jPanel1.add(signUpForLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\shazi\\Desktop\\prussian.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 470, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(966, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordForLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordForLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordForLoginActionPerformed

    private void instructorIdForLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorIdForLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instructorIdForLoginActionPerformed

    private void signInForLoginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInForLoginMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_signInForLoginMouseDragged

    private void signUpForLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpForLoginActionPerformed
        
        SignUpForm signUpForm = new SignUpForm();
        signUpForm.setVisible(true);
          Voice voice;
        VoiceManager vm = VoiceManager.getInstance();
        voice = vm.getVoice("kevin16");
        voice.allocate();
        voice.speak(" please enter your details for SignUp");
    }//GEN-LAST:event_signUpForLoginActionPerformed

    private void signInForLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInForLoginActionPerformed
          
         
       
    
        try {
                String select = "select * from Registration where UserName = ? and Password = ? and InstructorId = ? ";
                pst=conn.prepareStatement(select);
                pst.setString(1, userNameForLogin.getText());
                pst.setString(2, passwordForLogin.getText());
                pst.setString(3, instructorIdForLogin.getText());
                rs=pst.executeQuery();
                
              
                if(rs.next()&&jCheckBox1.isSelected())
                {
                      rs.close();
                    pst.close();
                    this.setVisible(false);
                    Loading ob = new Loading();
                    ob.setUpLoading();
                    ob.setVisible(true);
                     Voice voice;
        VoiceManager vm = VoiceManager.getInstance();
        voice = vm.getVoice("kevin16");
        voice.allocate();
        voice.speak("Please Wait");
       

                }else 
                {   
                    if(!jCheckBox1.isSelected())
                    {
                        JOptionPane.showMessageDialog(null, "You must accept terms and Conditions");
                    }
                    else
                        JOptionPane.showMessageDialog(null, "Incorrect Password and Username");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            finally
            {
                try {
                    rs.close();
                    pst.close();
                } catch (SQLException ex) {
                     JOptionPane.showMessageDialog(null, ex);
                }
            }
            
           
            
           
    }//GEN-LAST:event_signInForLoginActionPerformed

    private void userNameForLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameForLoginFocusGained
       userNameForLogin.setText("");
    }//GEN-LAST:event_userNameForLoginFocusGained

    private void passwordForLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordForLoginFocusGained
       passwordForLogin.setText("");
    }//GEN-LAST:event_passwordForLoginFocusGained

    private void instructorIdForLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_instructorIdForLoginFocusGained
            instructorIdForLogin.setText("");
    }//GEN-LAST:event_instructorIdForLoginFocusGained

    private void userNameForLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameForLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameForLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField instructorIdForLogin;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField passwordForLogin;
    private javax.swing.JButton signInForLogin;
    private javax.swing.JButton signUpForLogin;
    public static javax.swing.JTextField userNameForLogin;
    // End of variables declaration//GEN-END:variables
}
