/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gymmanagement;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author shazi
 */
public class SignUpForm extends javax.swing.JFrame {

        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
    public SignUpForm() {
        
        super("Registration");
        initComponents();
        conn=DBCONNECTION.ConnectDb();
        
        userNameOfRegistration.setBackground(new Color(0,0,0,0));
        NameOfRegistration.setBackground(new Color(0,0,0,0));
        instructorIdOfRegistration.setBackground(new Color(0,0,0,0));
        ContactNumberRegistration.setBackground(new Color(0,0,0,0));
        addressRegistration.setBackground(new Color(0,0,0,0));
        
        passwordRegistration.setBackground(new Color(0,0,0,0));
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        userNameOfRegistration = new javax.swing.JTextField();
        NameOfRegistration = new javax.swing.JTextField();
        instructorIdOfRegistration = new javax.swing.JTextField();
        RadioMaleRegistration = new javax.swing.JRadioButton();
        RadioFemaleRegistration = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ContactNumberRegistration = new javax.swing.JTextField();
        passwordRegistration = new javax.swing.JPasswordField();
        addressRegistration = new javax.swing.JTextField();
        registerButtion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Gym");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 120, 90));

        jLabel14.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Management");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel15.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("System");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\shazi\\Desktop\\cropped.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 450, 500));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Registration");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 240, 50));

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 100, -1));

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Instructor Id");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 70, -1));

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contact ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Address");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, -1));

        userNameOfRegistration.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        userNameOfRegistration.setForeground(new java.awt.Color(153, 153, 153));
        userNameOfRegistration.setText("Enter  Your User Name");
        userNameOfRegistration.setBorder(null);
        userNameOfRegistration.setOpaque(false);
        userNameOfRegistration.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameOfRegistrationFocusGained(evt);
            }
        });
        jPanel1.add(userNameOfRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 260, -1));

        NameOfRegistration.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        NameOfRegistration.setForeground(new java.awt.Color(153, 153, 153));
        NameOfRegistration.setText("Enter Your Name");
        NameOfRegistration.setBorder(null);
        NameOfRegistration.setOpaque(false);
        NameOfRegistration.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameOfRegistrationFocusGained(evt);
            }
        });
        jPanel1.add(NameOfRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 260, -1));

        instructorIdOfRegistration.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        instructorIdOfRegistration.setForeground(new java.awt.Color(153, 153, 153));
        instructorIdOfRegistration.setText("Enter Your Id");
        instructorIdOfRegistration.setBorder(null);
        instructorIdOfRegistration.setOpaque(false);
        instructorIdOfRegistration.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                instructorIdOfRegistrationFocusGained(evt);
            }
        });
        jPanel1.add(instructorIdOfRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 260, -1));

        RadioMaleRegistration.setOpaque(false);
        RadioMaleRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioMaleRegistrationActionPerformed(evt);
            }
        });
        jPanel1.add(RadioMaleRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, -1, -1));

        RadioFemaleRegistration.setOpaque(false);
        jPanel1.add(RadioFemaleRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 261, -1, -1));

        jLabel11.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Male");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, -1, -1));

        jLabel12.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Female");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 261, -1, -1));

        ContactNumberRegistration.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        ContactNumberRegistration.setForeground(new java.awt.Color(153, 153, 153));
        ContactNumberRegistration.setText("Enter Your Contact Number");
        ContactNumberRegistration.setBorder(null);
        ContactNumberRegistration.setOpaque(false);
        ContactNumberRegistration.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ContactNumberRegistrationFocusGained(evt);
            }
        });
        jPanel1.add(ContactNumberRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 260, -1));

        passwordRegistration.setForeground(new java.awt.Color(153, 153, 153));
        passwordRegistration.setText("jPasswordField1");
        passwordRegistration.setBorder(null);
        passwordRegistration.setOpaque(false);
        passwordRegistration.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordRegistrationFocusGained(evt);
            }
        });
        passwordRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordRegistrationActionPerformed(evt);
            }
        });
        jPanel1.add(passwordRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 260, -1));

        addressRegistration.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        addressRegistration.setForeground(new java.awt.Color(153, 153, 153));
        addressRegistration.setText("Enter Your Address");
        addressRegistration.setBorder(null);
        addressRegistration.setOpaque(false);
        addressRegistration.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressRegistrationFocusGained(evt);
            }
        });
        jPanel1.add(addressRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 260, -1));

        registerButtion.setBackground(new java.awt.Color(0, 51, 102));
        registerButtion.setForeground(new java.awt.Color(240, 240, 240));
        registerButtion.setText("Register");
        registerButtion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtionActionPerformed(evt);
            }
        });
        jPanel1.add(registerButtion, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 260, 10));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 260, 10));

        jSeparator3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 260, 10));

        jSeparator4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 260, 10));

        jSeparator5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 260, 10));

        jSeparator6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 260, 20));

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\shazi\\Desktop\\cropped2.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 490, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(946, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtionActionPerformed
            try {
                String insert = "insert into Registration(UserName,InstructorName,InstructorId,Gender,ContactNumber,Password,Address) values(?,?,?,?,?,?,?)"; 
                pst = conn.prepareCall(insert);
                pst.setString(1, userNameOfRegistration.getText());
                pst.setString(2, NameOfRegistration.getText());
                pst.setString(3, instructorIdOfRegistration.getText());
                if(RadioMaleRegistration.isEnabled())
                {
                    pst.setString(4, "Male");
                }
                else if (RadioFemaleRegistration.isEnabled()) {
                    pst.setString(4, "Female");
                }
                pst.setString(5, ContactNumberRegistration.getText());
                pst.setString(6, passwordRegistration.getText());
                pst.setString(7, addressRegistration.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "New Account Created");
               
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
               rs.close();
               pst.close();
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_registerButtionActionPerformed

    private void RadioMaleRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioMaleRegistrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioMaleRegistrationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
       Login login = new Login();
       login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void userNameOfRegistrationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameOfRegistrationFocusGained
        userNameOfRegistration.setText("");
    }//GEN-LAST:event_userNameOfRegistrationFocusGained

    private void NameOfRegistrationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameOfRegistrationFocusGained
        NameOfRegistration.setText("");
    }//GEN-LAST:event_NameOfRegistrationFocusGained

    private void instructorIdOfRegistrationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_instructorIdOfRegistrationFocusGained
        instructorIdOfRegistration.setText("");
    }//GEN-LAST:event_instructorIdOfRegistrationFocusGained

    private void ContactNumberRegistrationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContactNumberRegistrationFocusGained
        ContactNumberRegistration.setText("");
    }//GEN-LAST:event_ContactNumberRegistrationFocusGained

    private void passwordRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordRegistrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordRegistrationActionPerformed

    private void passwordRegistrationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordRegistrationFocusGained
       passwordRegistration.setText("");
    }//GEN-LAST:event_passwordRegistrationFocusGained

    private void addressRegistrationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressRegistrationFocusGained
       addressRegistration.setText("");
    }//GEN-LAST:event_addressRegistrationFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ContactNumberRegistration;
    private javax.swing.JTextField NameOfRegistration;
    private javax.swing.JRadioButton RadioFemaleRegistration;
    private javax.swing.JRadioButton RadioMaleRegistration;
    private javax.swing.JTextField addressRegistration;
    private javax.swing.JTextField instructorIdOfRegistration;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPasswordField passwordRegistration;
    private javax.swing.JButton registerButtion;
    private javax.swing.JTextField userNameOfRegistration;
    // End of variables declaration//GEN-END:variables
}
